### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Naviden** [AliOsm/simplerepresentations#3]
Doing `pip install simplerepresentation`, I get the following error:

```
ERROR: Could not find a version that satisfies the requirement simplerepresentation (from versions: none)
ERROR: No matching distribution found for simplerepresentation
```

Am I missing something?

**Comment by AliOsm** [comment]
It is working with me, could you please provide details about your os, python version, etc...?

**Comment by reinoldus** [comment]
there is a typo in the readme, the module is called simplerepresentations
https://pypi.org/project/simplerepresentations/

`pip install simplerepresentations`
